### ISSUE TITLE
Add HTTP GET urls for specific cases to allow easier uptime testing

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dartpad_server#20]
The uptime service requires JSON over POST which isn't our API def

**Comment by devoncarew** [comment]
http://kb.statuscake.com/hc/en-us/articles/201173152-How-to-Send-POST-Data

I _think_ statuscake will actually send it in application/x-www-form-urlencoded.

**Comment by lukechurch** [comment]
I looked at this article - unfortunately when you past non-JSON data into the field it reports: 
"The POST request must be valid JSON. Please see the knowledgebase for more information"

and the server doesn't actually seem to receive any POST data from statuscake
