### ISSUE TITLE
benchmarks running on each commit (and record the results)

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartpad_server#7]

**Comment by devoncarew** [comment]
They're running, but we need to send the benchmark results somewhere.

**Comment by lukechurch** [comment]
Are the results stored on a server somewhere? Anychance I could see them?

**Comment by devoncarew** [comment]
You can see them at the very end of each build:

https://travis-ci.org/dart-lang/dartpad_server

This item is tracking pushing them up to a service like Librato.

**Comment by sethladd** [comment]
librato... where have you been all my life?!?!

**Comment by devoncarew** [comment]
The dashboard could use some tweaking, but it shows:
- the benchmarks for the analysis service, run on each PR
- the benchmarks the the compiler server, run on each PR
- the compiled size of the app (run on each PR)

https://metrics.librato.com/share/dashboards/jr4dyv0j
